### ISSUE TITLE
"All activities" filter on maps only showing addresses

### ISSUE THREAD

**Issue by ssingh1997** [gcivil-nyu-org/Team_Team3_CS-GY-6063-Fall2021#208]
So when I filter for "basketball" on the maps, it shows me these blue markers on the map and if I hover over the, I see "see more info"

![image](https://user-images.githubusercontent.com/39809317/142456409-72d7cdf3-a5bb-43df-aa7f-ab97ba0a1fcc.png)

However, when i filter to "all activities" on the map, it shows me red markers on the map and if I hover over them, I only see the addresses.

![image](https://user-images.githubusercontent.com/39809317/142456564-f845b0ed-727f-44f6-9600-bb0dcdb7aad2.png)

**Comment by barksdaleaz** [comment]
Also seeing this! Might be nice to list the activities that each location offers (when viewing all activities). Otherwise hard to tell what is available at the space. Suppose you just want to browse and see what is near you, and you are open to playing whatever, but you can't join a game if you don't know what's nearby.
